#pragma once
#ifndef KERNEL_ANSI_H
#define KERNEL_ANSI_H

#include <stdint.h>

// 3-bit ANSI color codes
#define ANSI_COLOR_BLACK 0
#define ANSI_COLOR_RED 1
#define ANSI_COLOR_GREEN 2
#define ANSI_COLOR_YELLOW 3
#define ANSI_COLOR_BLUE 4
#define ANSI_COLOR_MAGENTA 5
#define ANSI_COLOR_CYAN 6
#define ANSI_COLOR_WHITE 7

static const uint32_t ANSI_3BIT_COLORS[8] = {
	0x000000, // ANSI_COLOR_BLACK
	0xaa0000, // ANSI_COLOR_RED
	0x00aa00, // ANSI_COLOR_GREEN
	0xaa5500, // ANSI_COLOR_YELLOW
	0x0000aa, // ANSI_COLOR_BLUE
	0xaa00aa, // ANSI_COLOR_MAGENTA
	0x00aaaa, // ANSI_COLOR_CYAN
	0xaaaaaa, // ANSI_COLOR_WHITE
};

// 4-bit ANSI color codes
#define ANSI_COLOR_BRIGHT_BLACK 8
#define ANSI_COLOR_BRIGHT_RED 9
#define ANSI_COLOR_BRIGHT_GREEN 10
#define ANSI_COLOR_BRIGHT_YELLOW 11
#define ANSI_COLOR_BRIGHT_BLUE 12
#define ANSI_COLOR_BRIGHT_MAGENTA 13
#define ANSI_COLOR_BRIGHT_CYAN 14
#define ANSI_COLOR_BRIGHT_WHITE 15

static const uint32_t ANSI_4BIT_COLORS[16] = {
	0x000000, // ANSI_COLOR_BLACK
	0xaa0000, // ANSI_COLOR_RED
	0x00aa00, // ANSI_COLOR_GREEN
	0xaa5500, // ANSI_COLOR_YELLOW
	0x0000aa, // ANSI_COLOR_BLUE
	0xaa00aa, // ANSI_COLOR_MAGENTA
	0x00aaaa, // ANSI_COLOR_CYAN
	0xaaaaaa, // ANSI_COLOR_WHITE
	0x555555, // ANSI_COLOR_BRIGHT_BLACK
	0xff5555, // ANSI_COLOR_BRIGHT_RED
	0x55ff55, // ANSI_COLOR_BRIGHT_GREEN
	0xffff55, // ANSI_COLOR_BRIGHT_YELLOW
	0x5555ff, // ANSI_COLOR_BRIGHT_BLUE
	0xff55ff, // ANSI_COLOR_BRIGHT_MAGENTA
	0x55ffff, // ANSI_COLOR_BRIGHT_CYAN
	0xffffff, // ANSI_COLOR_BRIGHT_WHITE
};

// 8-bit ANSI color codes
uint32_t ANSI_8BIT_COLORS[256];

#endif
